### ISSUE TITLE
Allow picking *videos* (seems only allow images now?)

### ISSUE THREAD

**Issue by fzyzcjy** [Sh1d0w/multi_image_picker#567] opened 2020-10-11 08:25 UTC
**Is your feature request related to a problem? Please describe.**
Hi thanks for this lib! It seems that the lib only shows images and hides videos. Thus I would appreciate it if videos could also be picked. Thanks!

**Describe the solution you'd like**
N/A

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by ufylord** [comment] 2020-10-26 21:32
#324

**Comment by ufylord** [comment] 2020-10-26 21:37
Duplicate of #324
Owner replied there:
> I don't plan to add support for this, however I can look into PR contributions enabling such functionality.
> 
> You are welcome to implement it.

**Closed** 2020-10-27 02:47 UTC
