### ISSUE TITLE
Image Picker does not show if permissions aren't granted until the app is restarted

### ISSUE THREAD

**Issue by derTuca** [Sh1d0w/multi_image_picker#59] opened 2019-01-14 11:47 UTC
**Describe the bug**
When opening the image picker, if the required permissions are not granted, the user is asked for the specific permissions (camera and external storage), and nothing happens even if they are granted. If I try to open it again, an exception is thrown, saying that the "Image picker is already active" until I restart the app.

**To Reproduce**
Do a fresh install of the app, so that no permissions are granted and run the below code.
```
selectedAssets = await MultiImagePicker.pickImages(maxImages: 20);
```

**Expected behavior**
After granting the permissions, I expected the picker to open.

**Flutter (please complete the following information):**
- Which version of `multi_image_picker` are you using: [e.g. 2.0.04]
2.3.29
```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel beta, v1.0.0, on Mac OS X 10.14.2 18C54, locale en-RO)
[✓] Android toolchain - develop for Android devices (Android SDK 28.0.3)
[✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
[✓] Android Studio (version 3.2)
[✓] IntelliJ IDEA Ultimate Edition (version 2018.3.3)
[✓] VS Code (version 1.30.2)
[✓] Connected device (1 available)

• No issues found!
```

**Android (please complete the following information):**
 - Device: Samsung Galaxy Note 8
 - OS: Oreo 8.0

**Additional context**
I managed to deter the issue by commenting the following if check:
```
private boolean setPendingMethodCallAndResult(MethodCall methodCall, MethodChannel.Result result) {
     // if (pendingResult != null) {
     // return false;
    // }

    this.methodCall = methodCall;
    pendingResult = result;
    return true;
}
```
Now the picker opens properly if I run the line stated in the reproduce section again.

**Comment by Sh1d0w** [comment] 2019-01-14 11:50
@derTuca This should already be fixed in the latest version of the plugin 2.3.31

Seems like you are using older version, can you try the latest one and reopen if you still experience the same issue?

**Comment by derTuca** [comment] 2019-01-14 12:08
The issue still occurs unfortunately, even after updating to the latest version.

**Comment by Sh1d0w** [comment] 2019-01-14 12:09
Ok I will take a look at it.

**Comment by Sh1d0w** [comment] 2019-01-14 12:37
I've also just release version 2.3.32 which may potentially fix your problem can you try it and let me know.

**Comment by Sh1d0w** [comment] 2019-01-18 02:46
Closing because if inactivity. If you still experience this error with the latest version, let me know how I can reproduce it.

**Closed by Sh1d0w** 2019-01-18 02:46 UTC
Labels: Waiting response
