### ISSUE TITLE
Didn't find class "com.sangcomz.fishbun.FishBunFileProvider"

### ISSUE THREAD

**Issue by mjkbsun** [Sh1d0w/multi_image_picker#190] opened 2019-07-04 02:25 UTC
运行example正常的,但是引入项目就会报错找不到这个库,我在External Libraries的multi_image_picker-4.3.4的 android目录的build.gradle里看到了对FishBun的引入,但是运行android依然会崩溃

**Comment by Sh1d0w** [comment] 2019-07-04 03:43
Closing as duplicate of https://github.com/Sh1d0w/multi_image_picker/issues/181

You have to migrate to Android X using Android Studio.

**Closed by Sh1d0w** 2019-07-04 03:43 UTC
