### ISSUE TITLE
Meta data GPS Latitude and Longitude data returns null

### ISSUE THREAD

**Issue by b-jan** [Sh1d0w/multi_image_picker#232] opened 2019-08-25 22:32 UTC
**Bug Report**

As https://sh1d0w.github.io/multi_image_picker/#/metadata steps

multi_image_picker version: 4.5.2 (same issue for older versions)

Is it happening on Android: Yes
Is it happening on iOS: ?

[✓] Flutter (Channel dev, v1.8.2, on Linux, locale fr_FR.UTF-8)
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.0)
[✓] Android Studio (version 3.4)
[!] IntelliJ IDEA Community Edition (version 2017.3)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
[✓] VS Code (version 1.33.1)
[✓] Connected device (1 available)
**Describe the bug**

Console out meta.gps.gpsLatitude and meta.gps.gpsLongitude} is null

I reopen this issue: https://github.com/Sh1d0w/multi_image_picker/issues/152#issue-445297732

In the requestMetada function I logged what was calculated by 
```
Map<dynamic, dynamic> map = await _channel.invokeMethod(
      "requestMetadata",
      <String, dynamic>{
        "identifier": identifier,
      },
    );
```

And what I find is:
```
Map (47 items)
...
GPSLatitude : 0.0
GPSLongitude : 0.0
...
```

On my phone, the picture has clearly the GPS location correct, featuring a map saying where the photo has been taken. So how can i get the GPS coordinates of my photo ?

**Comment by Sh1d0w** [comment] 2019-08-26 07:43
Hey, I will look into it when I have time. Can you provide example image that I can reproduce this with?

Meanwhile PRs are also welcome :)

**Comment by b-jan** [comment] 2019-08-26 08:05
![MVIMG_20190711_185641](https://user-images.githubusercontent.com/24225949/63675334-dfa54080-c7e8-11e9-91b9-62ba286b8dc6.jpg)

Here is an image example from the top of Eiffel Tower.

**Comment by b-jan** [comment] 2019-08-26 08:07
![image](https://user-images.githubusercontent.com/24225949/63675496-3ca0f680-c7e9-11e9-827e-f0fbbde5f195.png)

I tested it on http://metapicz.com/.

**Comment by b-jan** [comment] 2019-08-28 23:39
I investigated deeply into the android code.
Particularly in ExifInterface.java.

In the function `getExifAttribute(tag)` I found that the HashMap variable mAttributes does not contain any variable linked to GPS latitude or longitude. That's why getExifAttribute('TAG_GPS_LONGITUDE') is returning `null` resulting in a a default value 0.0 for the longitude in multiImagePickerPlugin.java.

See what the HashMap contains:

```
mAttributes = {HashMap[10]@20497} 
 0 = {HashMap@20508}  size = 11
  0 = {HashMap$Node@20520} "YResolution" -> "(URATIONAL, data length:8)"
  1 = {HashMap$Node@20521} "XResolution" -> "(URATIONAL, data length:8)"
  2 = {HashMap$Node@20522} "ImageWidth" -> "(ULONG, data length:4)"
  3 = {HashMap$Node@20523} "Model" -> "(STRING, data length:8)"
  4 = {HashMap$Node@20524} "ImageLength" -> "(ULONG, data length:4)"
  5 = {HashMap$Node@20525} "Make" -> "(STRING, data length:7)"
  6 = {HashMap$Node@20526} "Software" -> "(STRING, data length:21)"
  7 = {HashMap$Node@20527} "YCbCrPositioning" -> "(USHORT, data length:2)"
  8 = {HashMap$Node@20528} "Orientation" -> "(USHORT, data length:2)"
  9 = {HashMap$Node@20529} "ResolutionUnit" -> "(USHORT, data length:2)"
  10 = {HashMap$Node@20530} "DateTime" -> "(STRING, data length:20)"
 1 = {HashMap@20509}  size = 38
  0 = {HashMap$Node@20555} "ExifVersion" -> "(STRING, data length:4)"
  1 = {HashMap$Node@20556} "ApertureValue" -> "(URATIONAL, data length:8)"
  2 = {HashMap$Node@20557} "SceneType" -> "(UNDEFINED, data length:1)"
  3 = {HashMap$Node@20558} "SubjectDistanceRange" -> "(USHORT, data length:2)"
  4 = {HashMap$Node@20559} "ExposureBiasValue" -> "(SRATIONAL, data length:8)"
  5 = {HashMap$Node@20560} "ExposureProgram" -> "(USHORT, data length:2)"
  6 = {HashMap$Node@20561} "SubjectDistance" -> "(URATIONAL, data length:8)"
  7 = {HashMap$Node@20562} "ColorSpace" -> "(USHORT, data length:2)"
  8 = {HashMap$Node@20563} "MaxApertureValue" -> "(URATIONAL, data length:8)"
  9 = {HashMap$Node@20564} "PixelYDimension" -> "(USHORT, data length:2)"
  10 = {HashMap$Node@20565} "BrightnessValue" -> "(SRATIONAL, data length:8)"
  11 = {HashMap$Node@20566} "DateTimeOriginal" -> "(STRING, data length:20)"
  12 = {HashMap$Node@20567} "FlashpixVersion" -> "(UNDEFINED, data length:4)"
  13 = {HashMap$Node@20568} "MakerNote" -> "(UNDEFINED, data length:24559)"
  14 = {HashMap$Node@20569} "SubSecTimeOriginal" -> "(STRING, data length:7)"
  15 = {HashMap$Node@20570} "WhiteBalance" -> "(USHORT, data length:2)"
  16 = {HashMap$Node@20571} "CustomRendered" -> "(USHORT, data length:2)"
  17 = {HashMap$Node@20572} "ExposureMode" -> "(USHORT, data length:2)"
  18 = {HashMap$Node@20573} "ExposureTime" -> "(URATIONAL, data length:8)"
  19 = {HashMap$Node@20574} "Flash" -> "(USHORT, data length:2)"
  20 = {HashMap$Node@20575} "SubSecTime" -> "(STRING, data length:7)"
  21 = {HashMap$Node@20576} "FNumber" -> "(URATIONAL, data length:8)"
  22 = {HashMap$Node@20577} "PixelXDimension" -> "(USHORT, data length:2)"
  23 = {HashMap$Node@20578} "Saturation" -> "(USHORT, data length:2)"
  24 = {HashMap$Node@20579} "PhotographicSensitivity" -> "(USHORT, data length:2)"
  25 = {HashMap$Node@20580} "ComponentsConfiguration" -> "(UNDEFINED, data length:4)"
  26 = {HashMap$Node@20581} "FocalLengthIn35mmFilm" -> "(USHORT, data length:2)"
  27 = {HashMap$Node@20582} "SubSecTimeDigitized" -> "(STRING, data length:7)"
  28 = {HashMap$Node@20583} "Contrast" -> "(USHORT, data length:2)"
  29 = {HashMap$Node@20584} "Sharpness" -> "(USHORT, data length:2)"
  30 = {HashMap$Node@20585} "DigitalZoomRatio" -> "(URATIONAL, data length:8)"
  31 = {HashMap$Node@20586} "DateTimeDigitized" -> "(STRING, data length:20)"
  32 = {HashMap$Node@20587} "ShutterSpeedValue" -> "(SRATIONAL, data length:8)"
  33 = {HashMap$Node@20588} "MeteringMode" -> "(USHORT, data length:2)"
  34 = {HashMap$Node@20589} "FocalLength" -> "(URATIONAL, data length:8)"
  35 = {HashMap$Node@20590} "SceneCaptureType" -> "(USHORT, data length:2)"
  36 = {HashMap$Node@20591} "LightSource" -> "(ULONG, data length:4)"
  37 = {HashMap$Node@20592} "SensingMethod" -> "(USHORT, data length:2)"
 2 = {HashMap@20510}  size = 2
  0 = {HashMap$Node@20597} "GPSImgDirection" -> "(URATIONAL, data length:8)"
  1 = {HashMap$Node@20598} "GPSImgDirectionRef" -> "(STRING, data length:2)"
 3 = {HashMap@20511}  size = 1
  0 = {HashMap$Node@20602} "InteroperabilityIndex" -> "(STRING, data length:4)"
 4 = {HashMap@20512}  size = 9
  0 = {HashMap$Node@20605} "ThumbnailImageLength" -> "(USHORT, data length:2)"
  1 = {HashMap$Node@20606} "YResolution" -> "(URATIONAL, data length:8)"
  2 = {HashMap$Node@20607} "Compression" -> "(USHORT, data length:2)"
  3 = {HashMap$Node@20608} "JPEGInterchangeFormat" -> "(ULONG, data length:4)"
  4 = {HashMap$Node@20609} "JPEGInterchangeFormatLength" -> "(ULONG, data length:4)"
  5 = {HashMap$Node@20610} "XResolution" -> "(URATIONAL, data length:8)"
  6 = {HashMap$Node@20611} "ThumbnailImageWidth" -> "(USHORT, data length:2)"
  7 = {HashMap$Node@20612} "Orientation" -> "(USHORT, data length:2)"
  8 = {HashMap$Node@20613} "ResolutionUnit" -> "(USHORT, data length:2)"
 5 = {HashMap@20513}  size = 0
 6 = {HashMap@20514}  size = 0
 7 = {HashMap@20515}  size = 0
 8 = {HashMap@20516}  size = 0
 9 = {HashMap@20517}  size = 0
```

**Comment by b-jan** [comment] 2019-08-29 00:07
I now found that ths 0.0 is coming from the function `getLagLong(uri)`

```
private HashMap<String, Object> getLatLng(@NonNull Uri uri) {
        HashMap<String, Object> result = new HashMap<>();
        String latitudeStr = "latitude";
        String longitudeStr = "longitude";
        List<String> latlngList = Arrays.asList(latitudeStr, longitudeStr);

        int indexNotPresent = -1;

        String uriScheme = uri.getScheme();

        if (uriScheme == null) {
            return result;
        }

        if (uriScheme.equals("content")) {
            Cursor cursor = context.getContentResolver().query(uri, null, null, null, null);

            if (cursor == null) {
                return result;
            }

            try {
                String[] columnNames = cursor.getColumnNames();
                List<String> columnNamesList = Arrays.asList(columnNames);

                for (String latorlngStr : latlngList) {
                    cursor.moveToFirst();
                    int index = columnNamesList.indexOf(latorlngStr);
                    if (index > indexNotPresent) {
                        Double val = cursor.getDouble(index);
                        // Inserting it as abs as it is the ref the define if the value should be negative or positive
                        if (latorlngStr.equals(latitudeStr)) {
                            result.put(ExifInterface.TAG_GPS_LATITUDE, Math.abs(val));
                        } else {
                            result.put(ExifInterface.TAG_GPS_LONGITUDE, Math.abs(val));
                        }
                    }
                }
            } catch (NullPointerException e) {
                e.printStackTrace();
            } finally {
                try {
                    cursor.close();
                } catch (NullPointerException e) {
                    e.printStackTrace();
                }
            }
        }

        return result;
    }
```

The line `Double val = cursor.getDouble(index);` gives me 0.0.

Logging what is in the latitude `index`: (I never used Java)

```
11 = "latitude"
 count = 16
 hash = 0
 shadow$_klass_ = {Class@8604} "class java.lang.String"
  accessFlags = 524305
  classFlags = 5
  classLoader = null
  classSize = 672
  clinitThreadId = 0
  componentType = null
  copiedMethodsOffset = 96
  dexCache = {DexCache@20951} 
  dexClassDefIndex = 958
  dexTypeIndex = 349
  extData = null
  iFields = 1891131160
  ifTable = {Object[6]@20952} 
  methods = 1892071112
  name = "java.lang.String"
  numReferenceInstanceFields = 0
  numReferenceStaticFields = 2
  objectSize = 0
  objectSizeAllocFastPath = -1
  primitiveType = 131072
  referenceInstanceOffsets = 0
  sFields = 1891131108
  status = -536870912
  superClass = {Class@10185} "class java.lang.Object"
  virtualMethodsOffset = 41
  vtable = null
  shadow$_klass_ = {Class@10496} "class java.lang.Class"
  shadow$_monitor_ = -1398825804
 shadow$_monitor_ = 0
``` 

Is my latitude somewhere hidden here?

**Comment by b-jan** [comment] 2019-08-29 00:14
The function has been implemented on this issue : https://github.com/Sh1d0w/multi_image_picker/pull/153#issuecomment-525970132

**Comment by b-jan** [comment] 2019-09-07 21:33
@Quanalogy found a solution with the exif package on this!
https://github.com/Sh1d0w/multi_image_picker/pull/153#issuecomment-529099898

**Comment by b-jan** [comment] 2019-09-29 18:49
@Quanalogy @Sh1d0w 

Hello guys, by chance, did you have time to work on this issue?
I was busy for the last 3 weeks.
I now have a Mac to build my Flutter app on iOS!

**Comment by claudioredi** [comment] 2019-12-29 05:32
@Sh1d0w : this is related to [scoped storage](https://developer.android.com/about/versions/10/privacy/changes#scoped-storage) in Android 10

I have a pull request ready for this if you're interested.

**Comment by Sh1d0w** [comment] 2019-12-29 05:33
@claudioredi That sounds great, thanks for looking into this. Contributions are always welcome :)

**Comment by claudioredi** [comment] 2019-12-29 05:35
@Sh1d0w : I don't have a Android < 10 device to test it a little more. I know that works OK in Android 10 but I would like to test it more carefully to be as sure as possible that didn't introduce any regression :)

**Comment by claudioredi** [comment] 2019-12-29 05:46
Feel free to take an early look and let me know what you think! https://github.com/claudioredi/multi_image_picker/commit/fa4dbc0993384bce9198e017d9b6d0308cf5a590

**Comment by Sh1d0w** [comment] 2019-12-29 20:08
@claudioredi Seems legit, however it got me thinking that I might have approached this incorrectly now that we are adding even more permissions.

I don't think prompting the user the first time to allow all those permissions is a good UX, given the fact the developer might never need them. I mean ACCESS_MEDIA_LOCATION and CAMERA permissions are only needed if you use those two features, but it will prompt for them anyway.

I think I might just remove those prompts from the plugin at all and leave a section in the documentation what permissions are needed if you want to use given features of the picker.

Then it is up to the user to request them with plugins like https://pub.dev/packages/simple_permissions

What are your thought on this?

**Comment by claudioredi** [comment] 2019-12-29 20:19
@Sh1d0w: I really share your concern! I thought exactly the same but didn't find a better place to do it. 

I think the camera permission might be moved to a different place inside the framework. (Maybe when you actually tap on the icon to use the feature?)

I really agree that asking for ACCESS_MEDIA_LOCATION on media pick could be an overkill. Moving this specific permission logic outside the framework could be a good option as you suggest.

**Comment by Sh1d0w** [comment] 2020-01-04 07:04
@claudioredi Thanks for you help.

I've removed permission handling from the app at all, because newest version of FishBun handles permissions by itself. BSImagePicker already handled the permissions.

I've also left a note in the plugin docs regarding GPS permission as you advised https://sh1d0w.github.io/multi_image_picker/#/metadata

I think I can close this issue now.

**Comment by claudioredi** [comment] 2020-01-05 00:12
@Sh1d0w : glad to help! I'm a little confused though... asking for `ACCESS_MEDIA_LOCATION ` was only part of the fix. I also changed some code related of how we get the lat / long from picture for Android >= 10. Are you sure this can be closed without changing the code to read lst / long?  Maybe you have tested it on Android 10 and works but I think to remember that my change was necessary to make the GPS info work on my pixel 3.... could be wrong though!

**Comment by Sh1d0w** [comment] 2020-01-05 06:23
@claudioredi Ah, you are right. I thought you'd want to open a PR since this is your work involved there. Feel free to open one and I will release it as RC so people can test it before officially releasing.

I will also do some testing before I merge it. Sorry I think I've closed the issue too early.

**Comment by claudioredi** [comment] 2020-01-05 21:47
No problem, created pull request! Let me know how it goes :)

**Comment by Martibis** [comment] 2020-02-03 07:55
Any news on this?

**Comment by Sh1d0w** [comment] 2020-02-04 16:10
Hi.

@claudioredi awesome PR has been merged but I haven’t made official release including it yet. Will do that soon as I want to make some other improvements on the library.

Meanwhile you can reference the package but the master got branch in your pub spec if you want to help testing the fix.

**Closed** 2020-02-26 04:42 UTC
