### ISSUE TITLE
In the top right corner, when the image is deleted, the last image is always deleted.

### ISSUE THREAD

**Issue by gaojuanjuan** [Sh1d0w/multi_image_picker#58] opened 2019-01-14 09:44 UTC
![image](https://user-images.githubusercontent.com/14133759/51105270-8113ef00-1823-11e9-86d4-7afc68ea2b81.png)

```
setState(() {
                        print('索引${index}==========${imageList[index]}');
                        imageList.removeAt(index);
                      });
```
Above is the code called by clicking the delete button.

**Comment by Sh1d0w** [comment] 2019-01-14 09:47
This issue have nothing to do with the plugin. It is your code implementation.

Closing as duplicate of https://github.com/Sh1d0w/multi_image_picker/issues/36.

**Closed by Sh1d0w** 2019-01-14 09:47 UTC

**Comment by gaojuanjuan** [comment] 2019-01-14 09:51
I don't need the List<Asset> that you returned, when I replace it with other List tests, the object is deleted normally.
