### ISSUE TITLE
Out of set quantity

### ISSUE THREAD

**Issue by 12221010ll** [Sh1d0w/multi_image_picker#70] opened 2019-01-30 02:34 UTC
**Bug Report**

`multi_image_picker` version: 2.3.29

Is it happening on Android: Yes 

Is it happening on iOS: 

**Describe the bug**

When I'm using it，the 'maxImages' set 3,but when i click the fourth image,the program is exit.
sorry ,my English is poor.

**Comment by Sh1d0w** [comment] 2019-01-30 03:11
Duplicate of https://github.com/Sh1d0w/multi_image_picker/issues/54

**Closed by Sh1d0w** 2019-01-30 03:11 UTC
