### ISSUE TITLE
Android: Picker hangs running background task for pickImages.

### ISSUE THREAD

**Issue by gilgm12** [Sh1d0w/multi_image_picker#5] opened 2018-09-03 03:00 UTC
The following code hangs, for me.  After pressing "Sure" and picking two images, the picker goes away, as expected.  But, we never get a message back from the internal messenger, so we are stuck in the async pickImages routine forever.  Since this code lives in an onPress routine, pressing the button again results in an "already open" error.
```
                  List images;

                  images = await MultiImagePicker.pickImages(
                    maxImages: 30,
                  ).then((images){
                    print("Found images.");
                  }).catchError((error){
                    print("We had a problem! "+ error.message);
                  });
```

FD Results:
```
[√] Flutter (Channel beta, v0.6.0, on Microsoft Windows [Version 10.0.17134.228], locale en-US)
    • Flutter version 0.6.0 at D:\Projects\Mobile\flutter
    • Framework revision 9299c02cf7 (3 weeks ago), 2018-08-16 00:35:12 +0200
    • Engine revision e3687f70c7
    • Dart version 2.1.0-dev.0.0.flutter-be6309690f

[√] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    • Android SDK at C:\Users\Matt\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-27, build-tools 27.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b02)
    • All Android licenses accepted.

[√] Android Studio (version 3.1)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 27.1.1
    • Dart plugin version 173.4700
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b02)

[√] Connected devices (1 available)
    • Pixel XL • HT6960204853 • android-arm64 • Android 8.1.0 (API 27)

• No issues found!
```
Thoughts?

**Comment by Sh1d0w** [comment] 2018-09-03 03:57
Hi and thanks for opening the issue.

Can you please give me more info so I can reproduce the issue:

1. What version of the plugin are you using?
2. Are you running it in the emulator or a real device?
3. What Android version are you using?
4. Can you provide the two images you are trying to pick? Are they JPEGs?

**Comment by gilgm12** [comment] 2018-09-03 04:13
Hey, no problem.

Plugin version is 2.1.23.  I'm running on a real device - Android 8.1.0

Two of the images were png's, the other two are JPEG.  Just test images I pulled down from google.

**Comment by gilgm12** [comment] 2018-09-03 04:47
This issue happens regardless of image type, for me.

**Comment by gilgm12** [comment] 2018-09-03 04:50
Here are the five images I tried, in every combination.  Just attempted jpeg alone, unsuccessfully.

![chic_hand_lettered_table_number_gold_table_4-r465e8fe87c88487eb6d6db3e289ef97d_i40g8_8byvr_307](https://user-images.githubusercontent.com/622590/44967987-52dfe380-af02-11e8-9b41-c31212dd99b6.jpg)
![fb_img_1535883368286](https://user-images.githubusercontent.com/622590/44967996-5a9f8800-af02-11e8-9792-9e5c48e0d173.jpg)
![clipart-numbers-ntekyb8ta](https://user-images.githubusercontent.com/622590/44968003-655a1d00-af02-11e8-83b6-b550afd0ab05.png)
![number-2-clipart-red-rounded-square-with-number-2-md](https://user-images.githubusercontent.com/622590/44968004-6a1ed100-af02-11e8-9df3-2ed9b197665d.png)
![images](https://user-images.githubusercontent.com/622590/44968010-730fa280-af02-11e8-9192-63c797f3d628.png)

**Comment by Sh1d0w** [comment] 2018-09-03 05:03
Hey @gilgm12 . Just tried the above images in an emulator with Android 8, same as your emulator version and it worked just fine. But you said you are running it on a real device where the problem occurs. Can you tell me which Android version your device has?

Also do you see any error messages when you are trying to pick the images on your device? Can you try to listen for them by running `add shell logcat` from your terminal while picking them?

**Comment by Sh1d0w** [comment] 2018-11-03 04:35
I am closing this since I can't reproduce it. If you still face the same problem, please reopen with more info.

**Closed by Sh1d0w** 2018-11-03 04:35 UTC
Labels: bug
