### ISSUE TITLE
PlatformException(already_active, Image picker is already active, null

### ISSUE THREAD

**Issue by hana1234587** [Sh1d0w/multi_image_picker#517] opened 2020-08-06 07:29 UTC
New version appears

**Comment by dheeraj2dj** [comment] 2020-08-07 07:08
Have the same issue on `4.7.10`

**Comment by SergeiEensalu** [comment] 2020-08-09 11:11
The same error :)

**Comment by gs01md** [comment] 2020-08-11 01:02
me too

**Comment by Sh1d0w** [comment] 2020-08-11 06:54
Please provide steps to reproduce. I can't reproduce the error with the example app in this repo.

https://imgur.com/a/CtgtybG

**Comment by Firman95** [comment] 2020-08-13 04:57
@Sh1d0w how to reproduce:
- pick image using `enableCamera: true`
- dont select any image, just press cancel or back button on android
- pick image using  `enableCamera: true`, error : `PlatformException(already_active, Image picker is already active, null)`

Happens on `4.7.10`

**Comment by Sh1d0w** [comment] 2020-08-13 05:02
@Firman95 Which Flutter version are you running? I am on 1.17.5 and still can't reproduce it, see the video

https://imgur.com/a/VXlSLXm

**Comment by Firman95** [comment] 2020-08-13 05:07
@Sh1d0w flutter doctor -v:

```
[√] Flutter (Channel stable, v1.12.13+hotfix.7, on Microsoft Windows [Version 10.0.19041.450], locale en-US)
    • Flutter version 1.12.13+hotfix.7 at E:\flutter_windows_v1.12.13+hotfix.7-stable\flutter
    • Framework revision 9f5ff2306b (7 months ago), 2020-01-26 22:38:26 -0800
    • Engine revision a67792536c
    • Dart version 2.7.0

[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at C:\Users\Firman PC\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-30, build-tools 28.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Android Studio (version 4.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 47.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] Connected device (1 available)
    • LG H930 • LGH9304ef36c16 • android-arm64 • Android 8.0.0 (API 26)

```

**Comment by Sh1d0w** [comment] 2020-08-13 05:07
Thats pretty outdated version, can you update to the latest stable version and try again?

**Comment by Firman95** [comment] 2020-08-13 05:16
Later i can try to update the flutter SDK, but [this one](https://github.com/Sh1d0w/multi_image_picker/issues/517#issuecomment-670365976) have the same issue on flutter `v1.17.5`. 

This is the full error : 
```
E/flutter ( 6100): [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: PlatformException(already_active, Image picker is already active, null)
E/flutter ( 6100): #0      MultiImagePicker.pickImages (package:multi_image_picker/src/picker.dart:80:11)
E/flutter ( 6100): <asynchronous suspension>
E/flutter ( 6100): #1      FloorPlanPhotoScreenState._getImage (package:.....)

```

**Comment by Sh1d0w** [comment] 2020-08-13 05:17
@Firman95  Can you provide a repo that I can run and reproduce then? It might be caused by conflict with another plugin.

**Comment by tungtd95** [comment] 2020-08-13 13:35
@Firman95 you should remove image_picker

**Comment by MpEliaz** [comment] 2020-08-13 23:10
can i use this package together to image_picker? in same screen?

**Comment by Sh1d0w** [comment] 2020-08-14 03:06
@MpEliaz Yes, you should be able to.

**Comment by Firman95** [comment] 2020-08-14 05:23
@Sh1d0w unfortunately the issue doesnt occur with new project and flutter `v1.17.5`.

I tried to rollback all the package version and androidManifest from where this package still works on my project. Run `flutter clean` and syncing my android gradle folder, but this issue still comes up.

**Comment by coreysprague** [comment] 2020-08-17 16:05
Getting this as well on Flutter v1.20.2. Will try to provide more details to try to repro. 

Same steps as https://github.com/Sh1d0w/multi_image_picker/issues/517#issuecomment-673255896

**Comment by djguy4** [comment] 2020-08-18 05:40
I'm also getting this same problem in my project. I'm using multi_image_picker version 4.7.10
This is my flutter doctor result:
```
[✓] Flutter (Channel unknown, v1.17.5, on Mac OS X 10.15.5 19F101, locale en-AU)
    • Flutter version 1.17.5 at /Users/macbook/workspace/flutter
    • Framework revision 8af6b2f038 (7 weeks ago), 2020-06-30 12:53:55 -0700
    • Engine revision ee76268252
    • Dart version 2.8.4

 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/macbook/Library/Android/sdk
    • Platform android-30, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.6)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.6, Build version 11E708
    • CocoaPods version 1.8.4

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 47.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] Connected device (1 available)
    • MI 6 • 4171de09 • android-arm64 • Android 9 (API 28)
```

Using the same steps as https://github.com/Sh1d0w/multi_image_picker/issues/517#issuecomment-673255896

To help find the problem, I'm also including a stripped down version of my own project that still runs into this same problem:
https://github.com/djguy4/multi_image_problem

I hope this issue can be resolved soon because I'm delaying my deployment because of this issue. Thank you.

**Comment by saif97** [comment] 2020-08-18 17:22
I'm getting the same issue with the example provided in the package. Running the debugger, I've found out that _channel.invokeMethod() never returns any value even though  the picker screen closes [note the breakpoints in the image]
![image](https://user-images.githubusercontent.com/13847797/90544594-02fe9380-e190-11ea-97d4-57e142f0b9a0.png)

**Comment by jobweegink** [comment] 2020-08-19 18:42
I have the same issue, but i have the feeling that it's linked to [this](https://github.com/Sh1d0w/multi_image_picker/issues/520) issue as well

i first receive the error from the topic above and when i try to reopen the multi image picker i receive this warning
`PlatformException(already_active, Image picker is already active, null)`

here's my flutter doctor
`[✓] Flutter (Channel unknown, v1.17.5, on Mac OS X 10.15.5 19F101, locale en-GB)
    • Flutter version 1.17.5 at /Users/jobweegink/Development/flutter
    • Framework revision 8af6b2f038 (7 weeks ago), 2020-06-30 12:53:55 -0700
    • Engine revision ee76268252
    • Dart version 2.8.4

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/jobweegink/Library/Android/sdk
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.6)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.6, Build version 11E708
    • CocoaPods version 1.9.3

[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 44.0.2
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

[✓] VS Code (version 1.48.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.13.2

[✓] Connected device (1 available)
    • H8324 • BH900X60BZ • android-arm64 • Android 10 (API 29)`

**Comment by Sh1d0w** [comment] 2020-08-19 20:08
Hi, sorry for the delay.

@djguy4 Thanks for the example repo, I was able to reproduce the problem. The regression was caused by a PR that I've merged from contributor that added support for Flutter Embeding API v2. In his PR he removed the activity result listener by mistake for the backwards compatible v1 engine, thus this error. I should have released this as pre - release to be tested before that.

I've just released version 4.7.11 which should fix the issue. Please test and let me know.

**Closed** 2020-08-20 04:10 UTC
Labels: waiting response

**Comment by djguy4** [comment] 2020-08-24 02:29
@Sh1d0w Hello, sorry for the slow response. I've tested the new version and it is indeed working correctly now. I'll remove my repo now that the issue is fixed. Thank you for the fix!

**Comment by godilite** [comment] 2020-09-14 11:40
This issue is happening again in 4.7.13

**Comment by qalqal1212** [comment] 2020-10-18 14:40
Having the same issue in 4.7.14
