### ISSUE TITLE
Fails to run on Android(enableCamera: false): PERMISSION_PERMANENTLY_DENIED

### ISSUE THREAD

**Issue by acherkashyn** [Sh1d0w/multi_image_picker#92] opened 2019-03-20 21:29 UTC
**Bug Report**

`multi_image_picker` version: 3.0.23

Is it happening on Android: Yes

Is it happening on iOS: No

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, v1.2.1, on Mac OS X 10.14.3 18D42, locale en-US)
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
[✓] Android Studio (version 3.3)
[✓] IntelliJ IDEA Community Edition (version 2018.3.4)
[✓] VS Code (version 1.32.3)
[✓] Connected device (2 available)

• No issues found!
```

**Describe the bug**

Steps to reproduce:
* Create a sample app in Android Studio, delete all code in main.xml and paste this:

```
import 'package:flutter/material.dart';
import 'package:multi_image_picker/multi_image_picker.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Code Sample for material.RaisedButton',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: MyStatelessWidget(),
    );
  }
}

class MyStatelessWidget extends StatelessWidget {
  MyStatelessWidget({Key key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Center(
        child: Column(
          mainAxisSize: MainAxisSize.min,
          children: <Widget>[
            RaisedButton(
              onPressed: () { launchPhotoPicker(); },
              child: const Text('Pick photos'),
            ),
          ],
        ),
      ),
    );
  }

  void launchPhotoPicker() {
    MultiImagePicker.pickImages(
      maxImages: 10,
    );
  }
}
```

* Add permissions in AndroidManifest.xml:
```
    <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />
    <uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE" />
    <uses-permission android:name="android.permission.CAMERA" />
```

* Run the app on Android. I have a Google Pixel 2 with Android P. See one button on the screen
* Tap the button.

**Actual Result:**
* Shows a permission request screen, asking for one permission: Storage. Tap allow.
* Nothing happens, stays on the same screen.
* Log output:
```
14:19:56.415 1 info flutter.tools E/flutter (32759): [ERROR:flutter/lib/ui/ui_dart_state.cc(148)] Unhandled Exception: PlatformException(PERMISSION_PERMANENTLY_DENIED, Please enable access to the storage and the camera., null)
14:19:56.415 2 info flutter.tools E/flutter (32759): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:564:7)
14:19:56.415 3 info flutter.tools E/flutter (32759): #1      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:302:33)
14:19:56.415 4 info flutter.tools E/flutter (32759): <asynchronous suspension>
14:19:56.415 5 info flutter.tools E/flutter (32759): #2      MultiImagePicker.pickImages (package:multi_image_picker/picker.dart:45:24)
14:19:56.415 6 info flutter.tools E/flutter (32759): <asynchronous suspension>
14:19:56.415 7 info flutter.tools E/flutter (32759): #3      MyStatelessWidget.launchPhotoPicker (package:my_flutter_app/main.dart:44:22)
14:19:56.415 8 info flutter.tools E/flutter (32759): #4      MyStatelessWidget.build.<anonymous closure> (package:my_flutter_app/main.dart:34:31)
14:19:56.415 9 info flutter.tools E/flutter (32759): #5      _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:513:14)
14:19:56.415 10 info flutter.tools E/flutter (32759): #6      _InkResponseState.build.<anonymous closure> (package:flutter/src/material/ink_well.dart:568:30)
14:19:56.415 11 info flutter.tools E/flutter (32759): #7      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:120:24)
14:19:56.415 12 info flutter.tools E/flutter (32759): #8      TapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:242:9)
14:19:56.415 13 info flutter.tools E/flutter (32759): #9      TapGestureRecognizer.handlePrimaryPointer (package:flutter/src/gestures/tap.dart:175:7)
14:19:56.415 14 info flutter.tools E/flutter (32759): #10     PrimaryPointerGestureRecognizer.handleEvent (package:flutter/src/gestures/recognizer.dart:369:9)
14:19:56.415 15 info flutter.tools E/flutter (32759): #11     PointerRouter._dispatch (package:flutter/src/gestures/pointer_router.dart:73:12)
14:19:56.415 16 info flutter.tools E/flutter (32759): #12     PointerRouter.route (package:flutter/src/gestures/pointer_router.dart:101:11)
14:19:56.415 17 info flutter.tools E/flutter (32759): #13     _WidgetsFlutterBinding&BindingBase&GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:214:19)
14:19:56.415 18 info flutter.tools E/flutter (32759): #14     _WidgetsFlutterBinding&BindingBase&GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:192:22)
14:19:56.415 19 info flutter.tools E/flutter (32759): #15     _WidgetsFlutterBinding&BindingBase&GestureBinding._handlePointerEvent (package:flutter/src/gestures/binding.dart:149:7)
14:19:56.415 20 info flutter.tools E/flutter (32759): #16     _WidgetsFlutterBinding&BindingBase&GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:101:7)
14:19:56.415 21 info flutter.tools E/flutter (32759): #17     _WidgetsFlutterBinding&BindingBase&GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:85:7)
14:19:56.415 22 info flutter.tools E/flutter (32759): #18     _rootRunUnary (dart:async/zone.dart:1136:13)
14:19:56.415 23 info flutter.tools E/flutter (32759): #19     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
14:19:56.415 24 info flutter.tools E/flutter (32759): #20     _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
14:19:56.415 25 info flutter.tools E/flutter (32759): #21     _invoke1 (dart:ui/hooks.dart:223:10)
14:19:56.415 26 info flutter.tools E/flutter (32759): #22     _dispatchPointerDataPacket (dart:ui/hooks.dart:144:5)
14:19:56.415 27 info flutter.tools E/flutter (32759): 
```

* Expected result:
* Should launch multi image picker, like on iOS, without errors.

**Comment by Sh1d0w** [comment] 2019-03-21 08:09
Are you running this for the first time on this device? Have you denied permission before or manually turned them off?

This error means that the permission was permanently denied, and because how Android works, if it was once, the plugin can not show the permission popup. The only way to enable is to handle this error in your code and present an alter that the user have to manually grant permission to the camera for this app via settings.

For more info how permissions work see here https://developer.android.com/guide/topics/permissions/overview

I am closing this as this is not a bug in the plugin, rather you not handling that case correctly.

**Comment by acherkashyn** [comment] 2019-03-21 17:37
@Sh1d0w I'm running the app for the first time, I do see the permission request as I've written in the report:
_Shows a permission request screen, asking for one permission: Storage. Tap allow._
I am allowing the permission. I checked in permission settings for the app - Storage permission is allowed. With permission allowed, I reopen the app again, tap the button, nothing happens. Still the same error in the log.

**Comment by acherkashyn** [comment] 2019-03-21 18:21
@Sh1d0w Here's what I found out. I added `enableCamera:true` and some logging in `MultiImagePickerPlugin.java` `onRequestPermissionResult()` method:

```
@Override
    public boolean onRequestPermissionsResult(int requestCode, String[] permissions, int[] grantResults) {
        for (int i = 0; i < permissions.length; i++) {
            System.out.println(TAG + ": Permission status for " + permissions[i] + " : " + grantResults[i]);
        }
...
```

And in the log I see these lines printed:
```
11:15:05.890 32 info flutter.tools I/System.out(19068): MultiImagePickerPlugin: Permission status for android.permission.READ_EXTERNAL_STORAGE : 0
11:15:05.890 33 info flutter.tools I/System.out(19068): MultiImagePickerPlugin: Permission status for android.permission.WRITE_EXTERNAL_STORAGE : -1
11:15:05.890 34 info flutter.tools I/System.out(19068): MultiImagePickerPlugin: Permission status for android.permission.CAMERA : 0
```

Apparently Write External Storage permission is not being granted, and causes MultiImagePickerPlugin to throw an exception. My app is using AndroidX, I do see 2 permission requests: for Camera and for Storage, and I allow them both. Why would WRITE_EXTERNAL_STORAGE not be granted by Android OS, do you have any hints where I should look?

**Comment by acherkashyn** [comment] 2019-03-21 18:32
@Sh1d0w I found this open issue, there seems to be some kind of ongoing issue with requesting WRITE_EXTERNAL_STORAGE permission with other flutter plugins, Simple_Permissions and Permission:
https://stackoverflow.com/questions/54322030/storage-permission-in-flutter
This has to be related to this issue.

**Comment by Sh1d0w** [comment] 2019-03-21 18:39
@acherkashyn Thanks for the detailed report. I will further look into this issue to see if I can reproduce it.

**Comment by Sh1d0w** [comment] 2019-03-21 18:42
@acherkashyn can you see if this could be the problem https://stackoverflow.com/questions/49709463/api-26-write-external-storage-permission-is-always-denied

Can you try to run the example app in this repository and see if you can reproduce the issue? If you can not, then it may be related to some other plugin you are using?

**Comment by acherkashyn** [comment] 2019-03-21 20:48
@Sh1d0w Yes, adding `tools:remove="android:maxSdkVersion"` into the manifest for WRITE_EXTERNAL_STORAGE did the trick, it works now! Thank you for the advice!
Might be worth documenting this in the readme, though this is not an issue with multi image picker, but others may stumble upon this while adding this library. Thanks for your help!

**Closed** 2019-03-22 04:20 UTC

**Comment by kaxp** [comment] 2019-04-10 14:50
even adding tools:remove="android:maxSdkVersion", to manifest file.
 <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE"
        tools:remove="android:maxSdkVersion"/>

it's still not working, getting the error, Unhandled Exception: PlatformException(PERMISSION_PERMANENTLY_DENIED, Please enable access to the storage and the camera., null)

**Comment by Florence2016** [comment] 2019-04-11 05:49
same result here I've already followed what was in here: https://sh1d0w.github.io/multi_image_picker/#/androudtroubleshooting

still not working Please enable access to the storage and the camera.

**Comment by VolkerFried** [comment] 2019-04-11 15:50
> 
> 
> same result here I've already followed what was in here: https://sh1d0w.github.io/multi_image_picker/#/androudtroubleshooting
> 
> still not working Please enable access to the storage and the camera.

I had the same problem.
`> flutter clean` 
Fixed the problem
