### ISSUE TITLE
The getter 'filePath' isn't defined for the class 'Asset' after upgrading flutter from 1.9.1 to 1.12.13

### ISSUE THREAD

**Issue by khanhtd36** [Sh1d0w/multi_image_picker#353] opened 2019-12-18 05:46 UTC
**Bug Report**

`multi_image_picker` version: ^4.5.5
Is it happening on Android: Yes
Is it happening on iOS: DontKnow

```
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, v1.12.13+hotfix.5, on Microsoft Windows [Version
    10.0.18362.535], locale en-US)

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[√] Android Studio (version 3.5)
[√] VS Code (version 1.40.0)
[√] Proxy Configuration
[√] Connected device (1 available)

• No issues found!
```

**Describe the bug**

After upgrading flutter from 1.9.1 to 1.12.13, I run `flutter pub get` then build project, the error message appear:
```
Error: The getter 'filePath' isn't defined for the class 'Asset'.
 - 'Asset' is from 'package:multi_image_picker/src/asset.dart' ('/D:/program/flutter/.pub-cache/hosted/pub.dartlang.org/multi_image_picker-4.6.0/lib/src/asset.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'filePath'.
      final path = await file.filePath;
                              ^^^^^^^^
```

**Comment by Sh1d0w** [comment] 2019-12-18 05:47
Closing as duplicate of https://github.com/Sh1d0w/multi_image_picker/issues/337#issuecomment-563581173

**Closed by Sh1d0w** 2019-12-18 05:47 UTC
