### ISSUE TITLE
 getThumbByteData not working.

### ISSUE THREAD

**Issue by nguyenlinhnttu** [Sh1d0w/multi_image_picker#391] opened 2020-02-22 17:08 UTC
**Bug Report**

`multi_image_picker` version: m ulti_image_picker: ^4.6.1

Is it happening on Android: Won't Test

Is it happening on iOS:  YES

```
[✓] Flutter (Channel master, v1.13.7-pre.24, on Mac OS X 10.15.3 19D76, locale en-US)
    • Flutter version 1.13.7-pre.24 at /Users/NguyenLinh/Documents/flutter_development/flutter
    • Framework revision 0aed0b61a1 (7 weeks ago), 2020-01-03 17:53:54 -0800
    • Engine revision eb139936eb
    • Dart version 2.8.0 (build 2.8.0-dev.0.0 2f57602411)

[!] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/NguyenLinh/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses

[✓] Xcode - develop for iOS and macOS (Xcode 11.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.3, Build version 11C29
    • CocoaPods version 1.9.0.beta.2

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 40.1.2
    • Dart plugin version 191.8423
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
```

**Describe the bug**
``` ByteData byteData = await asset.getByteData(quality: 70);```
This method woking normal.
But
I want use getThumbByteData to reduce image size when send it to server but it not woking.
``` ByteData byteData = await asset.getThumbByteData(width, height, quality: 70);```

Pleae help me check it.

**Comment by Sh1d0w** [comment] 2020-02-22 17:23
Hi, please explain what exactly is not working. Are you getting any error?

**Comment by Sh1d0w** [comment] 2020-02-22 17:24
Btw this plugin supports Flutter only on stable channel, I see you are on master. Please use the stable channel and reopen this issue if it still exists.

**Comment by nguyenlinhnttu** [comment] 2020-02-23 02:27
> Hi, please explain what exactly is not working. Are you getting any error?



> Btw this plugin supports Flutter only on stable channel, I see you are on master. Please use the stable channel and reopen this issue if it still exists.

I have switch to stable channel, but it not woking, and not show error log :(

**Comment by nguyenlinhnttu** [comment] 2020-02-23 02:35
``` [✓] Flutter (Channel stable, v1.12.13+hotfix.8, on Mac OS X 10.15.3 19D76, locale en-US)
    • Flutter version 1.12.13+hotfix.8 at /Users/NguyenLinh/Documents/flutter_development/flutter
    • Framework revision 0b8abb4724 (11 days ago), 2020-02-11 11:44:36 -0800
    • Engine revision e1e6ced81d
    • Dart version 2.7.0

[!] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/NguyenLinh/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses

[✓] Xcode - develop for iOS and macOS (Xcode 11.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.3, Build version 11C29
    • CocoaPods version 1.9.0.beta.2

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 40.1.2
    • Dart plugin version 191.8423
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)```

**Comment by nguyenlinhnttu** [comment] 2020-02-23 02:37
@Sh1d0w  Please help me.

**Comment by Sh1d0w** [comment] 2020-02-23 04:22
That’s strange.

Are you testing on a simulator or a real device?
Can you try the example app in this repository and let me know if it works?

If you want my help I need to reproduce it first so if you can provide example repository where it happens that will be great.

**Comment by nguyenlinhnttu** [comment] 2020-02-23 04:25
@Sh1d0w  
I use real device: Samsung A7 Android 9.0
Simulator: iphone 11 pro max.
A both not working.
I have add breakpoint 
```ByteData byteData = await asset.getThumbByteData(300, 300, quality: 70);  ```
But not work.

**Comment by nguyenlinhnttu** [comment] 2020-02-23 04:26
``` 
       //ByteData byteData = await asset.getThumbByteData(300, 300, quality: 70);   **(NOT WORK)**
        ByteData byteData = await asset.getByteData(quality: 80);   **(WORKING NORMAL)**
        List<int> imageData = byteData.buffer.asUint8List();
        MultipartFile multipartFile = MultipartFile.fromBytes(
          'illustratedImageUrls',
          imageData,
          filename: asset.name,
          contentType: MediaType("image", "jpg"),
        );
        arrFiles.add(multipartFile);
      }
```

**Comment by nguyenlinhnttu** [comment] 2020-02-23 04:29
@Sh1d0w In your example  : https://github.com/Sh1d0w/multi_image_picker/blob/master/example/lib/main.dart

I don't see func : ByteData byteData = await asset.getThumbByteData(300, 300, quality: 70);

**Comment by Sh1d0w** [comment] 2020-02-23 04:35
So what is the value of `byteData` in the first case where you are requesting thumb byte data? 

It is really strange that you are not getting any error and even more it happens both on Android and iOS where I use completely different libraries for image picking.

Can you try to remove the plugin, run `flutter clean` and re-install it?

**Comment by nguyenlinhnttu** [comment] 2020-02-23 04:38
i will try to re- install plugin and clean.

**Comment by nguyenlinhnttu** [comment] 2020-02-23 04:47
@Sh1d0w Not working. 
I request thumbByte from List<Asset> result from plugin

**Comment by Sh1d0w** [comment] 2020-02-24 04:30
Did you try to run the example app in this repo?

**Comment by nguyenlinhnttu** [comment] 2020-02-24 04:35
In your example i dont see func : `ByteData byteData = await asset.getThumbByteData(300, 300, quality: 70);`

**Comment by nguyenlinhnttu** [comment] 2020-02-24 04:36
I have follow document : https://sh1d0w.github.io/multi_image_picker/#/imagedata

**Comment by Sh1d0w** [comment] 2020-02-24 04:36
It is using it via AssetThumb widget, just run the example, pick some images and let me know if you see them.

**Comment by nguyenlinhnttu** [comment] 2020-02-24 06:10
@Sh1d0w  AssetThumb working but i don't know what happen with only 

func `ByteData byteData = await asset.getThumbByteData(300, 300, quality: 70);`

**Comment by Sh1d0w** [comment] 2020-02-24 06:12
AssetThumb is calling that same function, see reference here https://github.com/Sh1d0w/multi_image_picker/blob/master/lib/src/asset_thumb.dart#L69

It seems like the problem is somewhere in your code if the example app is running fine. If you want me to help you further then I need you to provide example repository where I can run and reproduce the problem.

I am going to close this for the time being as there is no actual problem that I can reproduce and may be specific to your project or misuse.

**Closed by Sh1d0w** 2020-02-24 06:12 UTC

**Comment by nguyenlinhnttu** [comment] 2020-02-24 06:29
@Sh1d0w  Omg i got it.  
I got error because i clone Asset to new Object and it not working. 
Error Code not working.
`` for (Asset asset in arrAssets) {{
 byteData = await asset.getThumbByteData(width, height, quality: 80);
``
Now it working when i change to for i.
`  for (int i = 0; i < arrAsset.length; i++) {
 byteData = await arrAsset[i].getThumbByteData(width, height, quality: 80);
`

Thanks for your help..
Sorry for bothering you.

**Comment by temirfe** [comment] 2020-05-28 12:35
getThumbByteData makes fixed size of 300 by 300 no matter what width and height I give.

**Comment by Sh1d0w** [comment] 2020-05-28 18:51
@temirfe What version of the plugin are you using? Make sure you are using the latest one.

**Comment by temirfe** [comment] 2020-05-29 10:57
I'm using the latest one.
