### ISSUE TITLE
I can't get filePath after upgrade from 4.5.7 to 4.6.0

### ISSUE THREAD

**Issue by bhanuka96** [Sh1d0w/multi_image_picker#345] opened 2019-12-13 14:57 UTC
How to get filePath?

**Comment by Sh1d0w** [comment] 2019-12-13 15:43
Closing as duplicate of https://github.com/Sh1d0w/multi_image_picker/issues/337#issuecomment-563581173

**Closed by Sh1d0w** 2019-12-13 15:43 UTC
