### ISSUE TITLE
OS Error: Operation not permitted, errno = 1

### ISSUE THREAD

**Issue by zhiqiangpan** [Sh1d0w/multi_image_picker#321] opened 2019-11-22 09:02 UTC
Error：IOS11.1.2
[VERBOSE-2:ui_dart_state.cc(148)] Unhandled Exception: FileSystemException: Cannot retrieve length of file, path = '/var/mobile/Media/DCIM/100APPLE/IMG_0012.JPG' (OS Error: Operation not permitted, errno = 1)
#0      _File.throwIfError (dart:io/file_impl.dart:643:7)
#1      _File.lengthSync (dart:io/file_impl.dart:385:5)
----------------------------------------------------
my code：
var images = await MultiImagePicker.pickImages(maxImages: 1);
var imgPath = await images[0].filePath
int size = File(imgPath).lengthSync();

**Comment by Sh1d0w** [comment] 2019-11-22 10:55
Closing as duplicate of https://github.com/Sh1d0w/multi_image_picker/issues/319

Please use `getByteData` or `getThumbByteData` in order to retrieve the image data.

**Closed by Sh1d0w** 2019-11-22 10:55 UTC
