### ISSUE TITLE
Pure flutter project is no problem, but the pickImage method of mixed projects is unresponsive

### ISSUE THREAD

**Issue by fg2q1q3q** [Sh1d0w/multi_image_picker#470] opened 2020-05-27 09:13 UTC
Hello, thanks to open source the library.
However, I encountered a problem in use. The pure flutter project has no problems, but after mixing the native project, the same code to add pictures does not take effect, and the error is reported :`PlatformException(error, Parameter specified as non-null is null: method kotlin.jvm.internal.Intrinsics.checkParameterIsNotNull, parameter a
ctivity, null)`

**Comment by Sh1d0w** [comment] 2020-05-27 09:21
Thanks for the report, feel free to debug and provide a PR to fix this I will review it.

**Comment by fg2q1q3q** [comment] 2020-05-27 11:39
I guess it may be caused by the following code in the `MultiImagePickerPlugin.java` file
> FishBun.with(MultiImagePickerPlugin.this.activity)

In mixed projects `MultiImagePickerPlugin.this.activity` may be null

**Comment by Sh1d0w** [comment] 2020-05-27 11:58
FishBun expects an activity to be passed in order to present the picker. I don't have example mixed project currently, but in such case how we can obtain the activity? Every app has an activity.

Can you see if this comments make any difference? https://github.com/Sh1d0w/multi_image_picker/issues/456#issuecomment-631859317

**Comment by fg2q1q3q** [comment] 2020-05-27 12:08
I know that the reason for this problem may be because the native flutter is not attached to the activity but uses the flutterActivity provided by the system, but google official recommends that the library should still upgrade the flutterplugin to solve the problem
Please refer to [https://flutter.dev/docs/development/packages-and-plugins/plugin-api-migration](https://flutter.dev/docs/development/packages-and-plugins/plugin-api-migration)

**Comment by Sh1d0w** [comment] 2020-06-15 11:12
Feel free to open a PR to migrate the plugin to the new format. Currently I don't have a time to do it.

**Comment by Sh1d0w** [comment] 2020-07-21 11:41
This has been implemented https://github.com/Sh1d0w/multi_image_picker/pull/505

**Comment by deakjahn** [comment] 2020-07-22 16:34
@Sh1d0w Is 4.6.9 supposed to solve this? Because it doesn't yet look like it does. Right now it doesn't run on Android at all.

```
java.lang.IllegalArgumentException: Parameter specified as non-null is null: method kotlin.jvm.internal.Intrinsics.checkParameterIsNotNull, parameter activity
```

**Comment by Sh1d0w** [comment] 2020-07-22 17:15
Can you provide a repo which I can checkout and reproduce, please?

**Comment by deakjahn** [comment] 2020-07-22 18:11
I'll try to come up with one.

**Comment by deakjahn** [comment] 2020-07-22 18:48
Obvious. It works in a simple repro, it doesn't in my app. Well, the search goes on.

**Comment by deakjahn** [comment] 2020-07-22 20:58
@Sh1d0w I think I know. Still checking out to be sure but I think so.

You made it to handle the activity in the v2 embedding scenario all right. However, if somebody still uses the v1 embedding (for instance, because they use other plugins as well that are not all supporting v2 yet), the `activity` isn't handled at all.

Yep, that must be it. Int `registerWith()`, you should also pass

    instance.onAttachedToEngine(registrar.context(), registrar.messenger(), regisrar.activity());

and store it as expected.

**Comment by Sh1d0w** [comment] 2020-07-22 21:02
Thanks for digging into it. Would you open a PR and I will merge it.

**Comment by deakjahn** [comment] 2020-07-22 21:02
This seems to handle it:

    public static void registerWith(Registrar registrar) {
        MultiImagePickerPlugin instance = new MultiImagePickerPlugin();
        instance.onAttachedToEngine(registrar.context(), registrar.messenger(), registrar.activity());
    }

    private void onAttachedToEngine(Context applicationContext, BinaryMessenger binaryMessenger, Activity activity) {
        context = applicationContext;
        messenger = binaryMessenger;
        this.activity = activity;
        channel = new MethodChannel(binaryMessenger, CHANNEL_NAME);
        channel.setMethodCallHandler(this);
    }

    @Override
    public void onAttachedToEngine(FlutterPluginBinding binding) {
        onAttachedToEngine(binding.getApplicationContext(), binding.getBinaryMessenger(), null);
    }

**Comment by deakjahn** [comment] 2020-07-22 21:03
Well, if it's as simple as this above, and you could just copy and paste, would it really need a PR? Possible, of course, but really necessary? :-)

**Comment by deakjahn** [comment] 2020-07-22 21:05
It works with the above, confirmed. Well, if you really need the PR, I'm game, but it's simply just these few lines.

**Comment by Sh1d0w** [comment] 2020-07-23 04:47
> Well, if it's as simple as this above, and you could just copy and paste, would it really need a PR? Possible, of course, but really necessary? :-)

I am on a vacation and don't have my laptop with me. Thanks for the PR will review it.

**Comment by deakjahn** [comment] 2020-09-21 08:15
Keeping from being closed.

**Comment by Sh1d0w** [comment] 2020-09-21 09:01
Hi this was merged and should be available on the latest released version.

**Closed by Sh1d0w** 2020-09-21 09:01 UTC
Labels: need investigation
