### ISSUE TITLE
Cannot use with textfield

### ISSUE THREAD

**Issue by kafein** [Sh1d0w/multi_image_picker#114] opened 2019-04-08 11:04 UTC
**Bug Report**

`multi_image_picker` version: 4.0.2
Is it happening on Android: 
No
Is it happening on iOS: 
Yes
```
 Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel dev, v1.4.10, on Mac OS X 10.14.3 18D109, locale tr-TR)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[✓] iOS toolchain - develop for iOS devices (Xcode 10.2)
[✓] Android Studio (version 3.3)
[✓] IntelliJ IDEA Ultimate Edition (version 2018.3.5)
[✓] VS Code (version 1.33.0)
[✓] Connected device (1 available)

• No issues found!
```

**Describe the bug**
After picking images in IOS emulator, textfields becomes unresponsive. Before picking image everything is fine. Repro; clone example project, insert a TextField, try to type after picking image.

**Comment by Sh1d0w** [comment] 2019-04-08 11:06
Closing as duplicate of https://github.com/Sh1d0w/multi_image_picker/issues/27

This is not bug in this plugin, rather than a Flutter bug https://github.com/flutter/flutter/issues/21193

**Closed by Sh1d0w** 2019-04-08 11:06 UTC

**Comment by Sh1d0w** [comment] 2019-04-08 11:08
PS. See this issue for a temporary workaround https://github.com/Sh1d0w/multi_image_picker/issues/45#issuecomment-449866888
